In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

$$1. EDA$$

In [2]:
data=pd.read_csv("Car-details-v3.csv")
data

name  year  selling_price  km_driven    fuel  \
0           Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1     Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2         Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3        Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4           Maruti Swift VXI BSIII  2007         130000     120000  Petrol   
...                            ...   ...            ...        ...     ...   
8123             Hyundai i20 Magna  2013         320000     110000  Petrol   
8124         Hyundai Verna CRDi SX  2007         135000     119000  Diesel   
8125        Maruti Swift Dzire ZDi  2009         382000     120000  Diesel   
8126               Tata Indigo CR4  2013         290000      25000  Diesel   
8127               Tata Indigo CR4  2013         290000      25000  Diesel   

     seller_type transmission                 owner     mileage   engine  \
0     Individual       Manual           First Owner   23.4 kmpl  1248 CC   
1     Individual       Manual          Second Owner  21.14 kmpl  1498 CC   
2     Individual       Manual           Third Owner   17.7 kmpl  1497 CC   
3     Individual       Manual           First Owner   23.0 kmpl  1396 CC   
4     Individual       Manual           First Owner   16.1 kmpl  1298 CC   
...          ...          ...                   ...         ...      ...   
8123  Individual       Manual           First Owner   18.5 kmpl  1197 CC   
8124  Individual       Manual  Fourth & Above Owner   16.8 kmpl  1493 CC   
8125  Individual       Manual           First Owner   19.3 kmpl  1248 CC   
8126  Individual       Manual           First Owner  23.57 kmpl  1396 CC   
8127  Individual       Manual           First Owner  23.57 kmpl  1396 CC   

       max_power                     torque  seats  
0         74 bhp             190Nm@ 2000rpm    5.0  
1     103.52 bhp        250Nm@ 1500-2500rpm    5.0  
2         78 bhp      12.7@ 2,700(kgm@ rpm)    5.0  
3         90 bhp   22.4 kgm at 1750-2750rpm    5.0  
4       88.2 bhp      11.5@ 4,500(kgm@ rpm)    5.0  
...          ...                        ...    ...  
8123   82.85 bhp           113.7Nm@ 4000rpm    5.0  
8124     110 bhp  24@ 1,900-2,750(kgm@ rpm)    5.0  
8125    73.9 bhp             190Nm@ 2000rpm    5.0  
8126      70 bhp        140Nm@ 1800-3000rpm    5.0  
8127      70 bhp        140Nm@ 1800-3000rpm    5.0  

[8128 rows x 13 columns]

In [3]:
data.head()

name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2      Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3     Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4        Maruti Swift VXI BSIII  2007         130000     120000  Petrol   

  seller_type transmission         owner     mileage   engine   max_power  \
0  Individual       Manual   First Owner   23.4 kmpl  1248 CC      74 bhp   
1  Individual       Manual  Second Owner  21.14 kmpl  1498 CC  103.52 bhp   
2  Individual       Manual   Third Owner   17.7 kmpl  1497 CC      78 bhp   
3  Individual       Manual   First Owner   23.0 kmpl  1396 CC      90 bhp   
4  Individual       Manual   First Owner   16.1 kmpl  1298 CC    88.2 bhp   

                     torque  seats  
0            190Nm@ 2000rpm    5.0  
1       250Nm@ 1500-2500rpm    5.0  
2     12.7@ 2,700(kgm@ rpm)    5.0  
3  22.4 kgm at 1750-2750rpm    5.0  
4     11.5@ 4,500(kgm@ rpm)    5.0

In [4]:
data.shape

(8128, 13)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   name           8128 non-null   object 
 1   year           8128 non-null   int64  
 2   selling_price  8128 non-null   int64  
 3   km_driven      8128 non-null   int64  
 4   fuel           8128 non-null   object 
 5   seller_type    8128 non-null   object 
 6   transmission   8128 non-null   object 
 7   owner          8128 non-null   object 
 8   mileage        7907 non-null   object 
 9   engine         7907 non-null   object 
 10  max_power      7913 non-null   object 
 11  torque         7906 non-null   object 
 12  seats          7907 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 825.6+ KB


In [6]:
data=data.replace(['kmpl',''],"",regex=True)
print(data)

                              name  year  selling_price  km_driven    fuel  \
0           Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1     Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2         Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3        Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4           Maruti Swift VXI BSIII  2007         130000     120000  Petrol   
...                            ...   ...            ...        ...     ...   
8123             Hyundai i20 Magna  2013         320000     110000  Petrol   
8124         Hyundai Verna CRDi SX  2007         135000     119000  Diesel   
8125        Maruti Swift Dzire ZDi  2009         382000     120000  Diesel   
8126               Tata Indigo CR4  2013         290000      25000  Diesel   
8127               Tata Indigo CR4  2013         290000      25000  Diesel   

     seller_type transmission                 owner mileage   e

In [7]:
data['mileage']=pd.to_numeric(data['mileage'],errors="coerce")
print(data['mileage'].dtype)

float64


In [8]:
data=data.replace(['CC',''],"",regex=True)
print(data)

                              name  year  selling_price  km_driven    fuel  \
0           Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1     Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2         Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3        Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4           Maruti Swift VXI BSIII  2007         130000     120000  Petrol   
...                            ...   ...            ...        ...     ...   
8123             Hyundai i20 Magna  2013         320000     110000  Petrol   
8124         Hyundai Verna CRDi SX  2007         135000     119000  Diesel   
8125        Maruti Swift Dzire ZDi  2009         382000     120000  Diesel   
8126               Tata Indigo CR4  2013         290000      25000  Diesel   
8127               Tata Indigo CR4  2013         290000      25000  Diesel   

     seller_type transmission                 owner  mileage en

In [9]:
data['engine']=pd.to_numeric(data['engine'],errors='coerce')
print(data['engine'].dtype)

float64


In [10]:
data=data.replace(['bhp',''],"",regex=True)
print(data)

                              name  year  selling_price  km_driven    fuel  \
0           Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1     Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2         Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3        Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4           Maruti Swift VXI BSIII  2007         130000     120000  Petrol   
...                            ...   ...            ...        ...     ...   
8123             Hyundai i20 Magna  2013         320000     110000  Petrol   
8124         Hyundai Verna CRDi SX  2007         135000     119000  Diesel   
8125        Maruti Swift Dzire ZDi  2009         382000     120000  Diesel   
8126               Tata Indigo CR4  2013         290000      25000  Diesel   
8127               Tata Indigo CR4  2013         290000      25000  Diesel   

     seller_type transmission                 owner  mileage  e

In [11]:
data['max_power']=pd.to_numeric(data['max_power'],errors='coerce')
print(data['max_power'].dtype)

float64


In [12]:
data.head()

name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2      Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3     Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4        Maruti Swift VXI BSIII  2007         130000     120000  Petrol   

  seller_type transmission         owner  mileage  engine  max_power  \
0  Individual       Manual   First Owner    23.40  1248.0      74.00   
1  Individual       Manual  Second Owner    21.14  1498.0     103.52   
2  Individual       Manual   Third Owner    17.70  1497.0      78.00   
3  Individual       Manual   First Owner    23.00  1396.0      90.00   
4  Individual       Manual   First Owner    16.10  1298.0      88.20   

                     torque  seats  
0            190Nm@ 2000rpm    5.0  
1       250Nm@ 1500-2500rpm    5.0  
2     12.7@ 2,700(kgm@ rpm)    5.0  
3  22.4 kgm at 1750-2750rpm    5.0  
4     11.5@ 4,500(kgm@ rpm)    5.0

In [13]:
data=data.replace(['@',''],"",regex=True)
data=data.replace(['Nm',''],"",regex=True)
data=data.replace(['kgm',''],"",regex=True)
data=data.replace(['rpm',''],"",regex=True)
print(data.head())

                           name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2      Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3     Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4        Maruti Swift VXI BSIII  2007         130000     120000  Petrol   

  seller_type transmission         owner  mileage  engine  max_power  \
0  Individual       Manual   First Owner    23.40  1248.0      74.00   
1  Individual       Manual  Second Owner    21.14  1498.0     103.52   
2  Individual       Manual   Third Owner    17.70  1497.0      78.00   
3  Individual       Manual   First Owner    23.00  1396.0      90.00   
4  Individual       Manual   First Owner    16.10  1298.0      88.20   

               torque  seats  
0            190 2000    5.0  
1       250 1500-2500    5.0  
2       12.7 2,700( )  

In [14]:
data['torque']=pd.to_numeric(data['torque'],errors='coerce')
print(data['torque'].dtype)

float64


In [15]:
data.describe()

year  selling_price     km_driven      mileage       engine  \
count  8128.000000   8.128000e+03  8.128000e+03  7819.000000  7907.000000   
mean   2013.804011   6.382718e+05  6.981951e+04    19.390375  1458.625016   
std       4.044249   8.062534e+05  5.655055e+04     4.001777   503.916303   
min    1983.000000   2.999900e+04  1.000000e+00     0.000000   624.000000   
25%    2011.000000   2.549990e+05  3.500000e+04    16.780000  1197.000000   
50%    2015.000000   4.500000e+05  6.000000e+04    19.300000  1248.000000   
75%    2017.000000   6.750000e+05  9.800000e+04    22.320000  1582.000000   
max    2020.000000   1.000000e+07  2.360457e+06    42.000000  3604.000000   

         max_power      torque        seats  
count  7912.000000   34.000000  7907.000000  
mean     91.517919  402.352941     5.416719  
std      35.822499   13.719887     0.959588  
min       0.000000  400.000000     2.000000  
25%      68.050000  400.000000     5.000000  
50%      82.000000  400.000000     5.000000  
75%     102.000000  400.000000     5.000000  
max     400.000000  480.000000    14.000000

In [16]:
data.isnull().sum()

name                0
year                0
selling_price       0
km_driven           0
fuel                0
seller_type         0
transmission        0
owner               0
mileage           309
engine            221
max_power         216
torque           8094
seats             221
dtype: int64

In [17]:
data.dropna(axis=0,inplace=True)
data

name  year  selling_price  km_driven    fuel  \
145           Volvo XC40 D4 R-Design  2018        3400000      22000  Diesel   
374   Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
413   Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
650   Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
1081  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
1100  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
1119  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
1138  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
1713  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
1828  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
2634  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
2667  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
3082  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
3251          Volvo XC40 D4 R-Design  2018        3400000      22000  Diesel   
3412  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
3520  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
3835  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
4219  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
4238  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
4259  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
4324  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
4418  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
4819  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
5087  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
5618  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
6170  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
6213  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
6558  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
6577  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
6693  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
6963  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
7516  Volvo XC60 Inscription D5 BSIV  2018        5500000      50000  Diesel   
7862  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
7930   Volvo S90 D4 Inscription BSIV  2019        5500000      17000  Diesel   

     seller_type transmission        owner  mileage  engine  max_power  \
145       Dealer    Automatic  First Owner     18.0  1969.0      190.0   
374   Individual    Automatic  First Owner     18.0  1969.0      190.0   
413   Individual    Automatic  First Owner     18.0  1969.0      190.0   
650   Individual    Automatic  First Owner     18.0  1969.0      190.0   
1081  Individual    Automatic  First Owner     18.0  1969.0      190.0   
1100  Individual    Automatic  First Owner     18.0  1969.0      190.0   
1119  Individual    Automatic  First Owner     18.0  1969.0      190.0   
1138  Individual    Automatic  First Owner     18.0  1969.0      190.0   
1713  Individual    Automatic  First Owner     18.0  1969.0      190.0   
1828  Individual    Automatic  First Owner     18.0  1969.0      190.0   
2634  Individual    Automatic  First Owner     18.0  1969.0      190.0   
2667  Individual    Automatic  First Owner     18.0  1969.0      190.0   
3082  Individual    Automatic  First Owner     18.0  1969.0      190.0   
3251      Dealer    Automatic  First Owner     18.0  1969.0      190.0   
3412  Individual    Automatic  First Owner     18.0  1969.0      190.0   
3520  Individual    Automatic  First Owner     

In [18]:
data.var()

year             8.288770e-02
selling_price    1.788235e+11
km_driven        2.693137e+07
mileage          1.360000e+00
engine           0.000000e+00
max_power        5.955882e+01
torque           1.882353e+02
seats            0.000000e+00
dtype: float64

In [19]:
data.head()

name  year  selling_price  km_driven    fuel  \
145           Volvo XC40 D4 R-Design  2018        3400000      22000  Diesel   
374   Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
413   Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
650   Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   
1081  Volvo XC40 D4 Inscription BSIV  2019        3800000      20000  Diesel   

     seller_type transmission        owner  mileage  engine  max_power  \
145       Dealer    Automatic  First Owner     18.0  1969.0      190.0   
374   Individual    Automatic  First Owner     18.0  1969.0      190.0   
413   Individual    Automatic  First Owner     18.0  1969.0      190.0   
650   Individual    Automatic  First Owner     18.0  1969.0      190.0   
1081  Individual    Automatic  First Owner     18.0  1969.0      190.0   

      torque  seats  
145    400.0    5.0  
374    400.0    5.0  
413    400.0    5.0  
650    400.0    5.0  
1081   400.0    5.0

In [20]:
final=data.drop(['fuel','seller_type','name','transmission','owner'],axis=1)

In [21]:
final

year  selling_price  km_driven  mileage  engine  max_power  torque  \
145   2018        3400000      22000     18.0  1969.0      190.0   400.0   
374   2019        3800000      20000     18.0  1969.0      190.0   400.0   
413   2019        3800000      20000     18.0  1969.0      190.0   400.0   
650   2019        3800000      20000     18.0  1969.0      190.0   400.0   
1081  2019        3800000      20000     18.0  1969.0      190.0   400.0   
1100  2019        3800000      20000     18.0  1969.0      190.0   400.0   
1119  2019        3800000      20000     18.0  1969.0      190.0   400.0   
1138  2019        3800000      20000     18.0  1969.0      190.0   400.0   
1713  2019        3800000      20000     18.0  1969.0      190.0   400.0   
1828  2019        3800000      20000     18.0  1969.0      190.0   400.0   
2634  2019        3800000      20000     18.0  1969.0      190.0   400.0   
2667  2019        3800000      20000     18.0  1969.0      190.0   400.0   
3082  2019        3800000      20000     18.0  1969.0      190.0   400.0   
3251  2018        3400000      22000     18.0  1969.0      190.0   400.0   
3412  2019        3800000      20000     18.0  1969.0      190.0   400.0   
3520  2019        3800000      20000     18.0  1969.0      190.0   400.0   
3835  2019        3800000      20000     18.0  1969.0      190.0   400.0   
4219  2019        3800000      20000     18.0  1969.0      190.0   400.0   
4238  2019        3800000      20000     18.0  1969.0      190.0   400.0   
4259  2019        3800000      20000     18.0  1969.0      190.0   400.0   
4324  2019        3800000      20000     18.0  1969.0      190.0   400.0   
4418  2019        3800000      20000     18.0  1969.0      190.0   400.0   
4819  2019        3800000      20000     18.0  1969.0      190.0   400.0   
5087  2019        3800000      20000     18.0  1969.0      190.0   400.0   
5618  2019        3800000      20000     18.0  1969.0      190.0   400.0   
6170  2019        3800000      20000     18.0  1969.0      190.0   400.0   
6213  2019        3800000      20000     18.0  1969.0      190.0   400.0   
6558  2019        3800000      20000     18.0  1969.0      190.0   400.0   
6577  2019        3800000      20000     18.0  1969.0      190.0   400.0   
6693  2019        3800000      20000     18.0  1969.0      190.0   400.0   
6963  2019        3800000      20000     18.0  1969.0      190.0   400.0   
7516  2018        5500000      50000     11.2  1969.0      235.0   480.0   
7862  2019        3800000      20000     18.0  1969.0      190.0   400.0   
7930  2019        5500000      17000     18.0  1969.0      190.0   400.0   

      seats  
145     5.0  
374     5.0  
413     5.0  
650     5.0  
1081    5.0  
1100    5.0  
1119    5.0  
1138    5.0  
1713    5.0  
1828    5.0  
2634    5.0  
2667    5.0  
3082    5.0  
3251    5.0  
3412    5.0  
3520    5.0  
3835    5.0  
4219    5.0  
4238    5.0  
4259    5.0  
4324    5.0  
4418    5.0  
4819    5.0  
5087    5.0  
5618    5.0  
6170    5.0  
6213    5.0  
6558    5.0  
6577    5.0  
6693    5.0  
6963    5.0  
7516    5.0  
7862    5.0  
7930    5.0

In [22]:
final.dtypes

year               int64
selling_price      int64
km_driven          int64
mileage          float64
engine           float64
max_power        float64
torque           float64
seats            float64
dtype: object

$$ 2. Statistical analysis$$

In [23]:
features=final.iloc[:,:-1].values
labels=final.iloc[:,-1].values

In [24]:
from sklearn.feature_selection import SelectKBest,chi2

In [25]:
for i in range(1,len(final.columns)-1):
    sel=SelectKBest(chi2,k=i)
    col=sel.fit_transform(features,labels)
    print(col)

[[400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [400.]
 [480.]
 [400.]
 [400.]]
[[190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [190. 400.]
 [235. 480.]
 [190. 400.]
 [190. 400.]]
[[1969.  190.  400.]
 [1969.  190.  400.]
 [1969.  190.  400.]
 [1969.  190.  400.]
 [1969.  190.  400.]
 [1969.  190.  400.]
 [1969.  190.  400.]
 [1969.  190.  400.]
 [1969.  190.  400.]
 [1969.  190.  400.]
 [1969.  190.  400.]
 [1969.  190.  400.]
 [1969.  190.  400.]
 [1969.  19

$$3. Build the model$$

In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(
   features,labels,test_size=0.2
)

$$ 4. Training and Testing$$

In [27]:
from sklearn.linear_model import LinearRegression

In [28]:
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [29]:
y_pred=lr.predict(x_test)

In [30]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_pred,y_test))
print(classification_report(y_test,y_pred))

1.0
              precision    recall  f1-score   support

         5.0       1.00      1.00      1.00         7

    accuracy                           1.00         7
   macro avg       1.00      1.00      1.00         7
weighted avg       1.00      1.00      1.00         7

